import { Header } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Sanchez, Catamaran, Kameron } from 'next/font/google';

const sanchez = Sanchez({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-sanchez',
});
const catamaran = Catamaran({
  subsets: ['latin'],
  weight: ['400', '600', '500'],
  variable: '--font-catamaran',
});
const kameron = Kameron({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-kameron',
});

export const metadata: Metadata = {
  title: 'Glitch Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${sanchez.variable} ${catamaran.variable} ${kameron.variable}`}
    >
      <body>
        <Header />
        <main className="px-4 md:px-0">{children}</main>
      </body>
    </html>
  );
}
